language: node_js
node_js: node
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database transactions;' -U postgres
script:
  - yarn install
  - yarn test
after_success:
  - yarn run coverage
   